repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [ --fix ]
        stages: [ pre-push, pre-commit ]
      - id: ruff-format
        # Removed --check to allow silent fixing of formatting issues
        stages: [ pre-push, pre-commit ]

  - repo: local
    hooks:
      - id: pytest-check
        name: Run Project-Wide Pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [ pre-push ]
