repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest-check
        name: Run Project-Wide Pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [ pre-push ]
