services:
  messaging-service:
    build:
      context: ../../../
      dockerfile: services/messaging_service/Dockerfile
    container_name: messaging_service
    restart: unless-stopped
    ports:
      - "8003:8003"
    env_file:
      - ../../../.env
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m
