"""Add signup session table

Revision ID: 45b140fb9980
Revises: 3ea359b7d5cb
Create Date: 2026-04-03 03:25:41.040837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b140fb9980'
down_revision: Union[str, Sequence[str], None] = '3ea359b7d5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_sessions',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('interests', sa.String(length=50), nullable=True),
    sa.Column('fx_capital', sa.Float(), nullable=True),
    sa.Column('stocks_capital', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signup_sessions')
    # ### end Alembic commands ###
