services:
  mt5-service:
    build:
      context: ../../../
      dockerfile: services/mt5_service/Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-danielmtzbarba}/mt5_service:latest
    container_name: mt5_service
    network_mode: "host"
    env_file: .env
    restart: unless-stopped
    environment:
      - WINEDEBUG=-all
      - PYTHONUNBUFFERED=1
      - ALSA_CARD=None
      - WINEDLLOVERRIDES=mciavi32,mciseq,mciwave,winealsa.drv,winepulse.drv=d

  sync-service:
    build:
      context: ../../../
      dockerfile: services/sync_service/Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-danielmtzbarba}/sync_service:latest
    container_name: sync_service
    network_mode: "host"
    env_file: .env
    environment:
      - MT5_SERVICE_URL=http://localhost:8000
      - INFLUX_URL=http://localhost:8086
    depends_on:
      - mt5-service
      - influxdb-mt5
    restart: unless-stopped

  influxdb-mt5:
    image: influxdb:2.7
    container_name: influxdb_mt5
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    deploy:
      resources:
        limits:
          memory: 350M
    ports:
      - "8086:8086"

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    deploy:
      resources:
        limits:
          memory: 64m
        reservations:
          memory: 32m

volumes:
  influxdb_data:
