services:
  mt5-engine:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/mt5-engine:latest
    container_name: mt5_engine
    network_mode: "host"
    env_file: .env
    restart: unless-stopped
    dns:
      - 100.100.100.100
      - 1.1.1.1 # Fallback for normal internet
    environment:
      - WINEDEBUG=-all          # This silences the Toolbar errors
      - PYTHONUNBUFFERED=1      # Ensures your Python logs show up immediately
      - ALSA_CARD=None          # Helps suppress some ALSA noise
      - WINEDLLOVERRIDES=mciavi32,mciseq,mciwave=d

  influxdb-mt5:
    image: influxdb:2.7
    container_name: influxdb_mt5
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2

    deploy:
      resources:
        limits:
          memory: 350M
    ports:
    - "8086:8086"

volumes:
  influxdb_data:
