"""add_type_to_positions

Revision ID: 39034e24f0a1
Revises: 49eb1d5383fe
Create Date: 2026-04-04 05:40:57.673192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39034e24f0a1"
down_revision: Union[str, Sequence[str], None] = "49eb1d5383fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("positions", sa.Column("type", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "type")
    # ### end Alembic commands ###
