"""add_active_status_to_positions

Revision ID: 49eb1d5383fe
Revises: c84a5ae626ef
Create Date: 2026-04-04 05:28:00.595342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49eb1d5383fe'
down_revision: Union[str, Sequence[str], None] = 'c84a5ae626ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable
    op.add_column('positions', sa.Column('active_status', sa.Boolean(), nullable=True))
    
    # 2. Set default value for existing rows
    op.execute("UPDATE positions SET active_status = true")
    
    # 3. Alter to NOT NULL
    op.alter_column('positions', 'active_status', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'active_status')
    # ### end Alembic commands ###
