"""Add market field to alerts and watchlist

Revision ID: c84a5ae626ef
Revises: 45b140fb9980
Create Date: 2026-04-03 04:14:38.552573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84a5ae626ef'
down_revision: Union[str, Sequence[str], None] = '45b140fb9980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('market', sa.String(length=10), nullable=False))
    op.add_column('watchlist', sa.Column('market', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('uq_user_stock'), 'watchlist', type_='unique')
    op.create_unique_constraint('uq_user_stock_market', 'watchlist', ['user_id', 'stock_id', 'market'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_stock_market', 'watchlist', type_='unique')
    op.create_unique_constraint(op.f('uq_user_stock'), 'watchlist', ['user_id', 'stock_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('watchlist', 'market')
    op.drop_column('alerts', 'market')
    # ### end Alembic commands ###
