services:
  execution-service:
    build:
      context: ../../../
      dockerfile: services/execution_service/Dockerfile
    container_name: execution_service
    restart: unless-stopped
    ports:
      - "8002:8002"
    env_file:
      - ../../../.env
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m
