services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ../../../.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    command: >
      postgres
      -c shared_buffers=256MB
      -c work_mem=8MB
      -c maintenance_work_mem=64MB
      -c effective_cache_size=512MB
      -c max_connections=50

  core-service:
    build:
      context: ../../../
      dockerfile: services/core_service/Dockerfile
    container_name: core_service
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - ../../../.env
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m

volumes:
  postgres_data:
